[webservers]web-1 ansible_host= fqdn=fhm1kps96or512vdpc2s.auto.internalweb-2 ansible_host= fqdn=fhmhcquuk62a7euesnlb.auto.internal
[databases]main ansible_host= fqdn=fhm9slp3pdf9jors46on.auto.internalreplica ansible_host= fqdn=fhmeo8cai2hdvmdc0m0r.auto.internal
[storage]storage ansible_host= fqdn=fhmstp1sflb2jbd1241f.auto.internal
